### PR TITLE
More doc formatting for Version 1.0.

### PR DESCRIPTION
**Pull request by moorepants**

### CODE REVIEW

**Comment by moorepants** [comment]
@brocksam Here are some more formatting improvements. Ready for review.

**Comment by moorepants** [comment]
Oddly getting a test failure:

```
============================= test session starts ==============================

platform linux -- Python 3.9.2, pytest-6.2.2, py-1.10.0, pluggy-0.13.1

rootdir: /home/travis/build/mechmotum/cyipopt, configfile: pytest.ini, testpaths: cyipopt/tests

collected 10 items                                                             

cyipopt/tests/integration/test_hs071.py .                                [ 10%]

cyipopt/tests/unit/test_deprecations.py .....                            [ 60%]

cyipopt/tests/unit/test_scipy_optional.py Fsss                           [100%]

=================================== FAILURES ===================================

_________________ test_minimize_ipopt_import_error_if_no_scipy _________________

    @pytest.mark.skipif("scipy" in sys.modules,

                        reason="Test only valid if no Scipy available.")

    def test_minimize_ipopt_import_error_if_no_scipy():

        """`minimize_ipopt` not callable without SciPy installed."""

        expected_error_msg = re.escape("Install SciPy to use the "

                                       "`minimize_ipopt` function.")

        with pytest.raises(ImportError, match=expected_error_msg):

>           cyipopt.minimize_ipopt(None, None)

cyipopt/tests/unit/test_scipy_optional.py:25: 

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

fun = None, x0 = None, args = (), kwargs = None, method = None, jac = None

hess = None, hessp = None, bounds = None, constraints = (), tol = None

callback = None, options = None

    def minimize_ipopt(fun, x0, args=(), kwargs=None, method=None, jac=None,

                       hess=None, hessp=None, bounds=None, constraints=(),

                       tol=None, callback=None, options=None):

        """

        Minimize a function using ipopt. The call signature is exactly like for

        ``scipy.optimize.mimize``. In options, all options are directly passed to

        ipopt. Check [http://www.coin-or.org/Ipopt/documentation/node39.html] for

        details. The options ``disp`` and ``maxiter`` are automatically mapped to

        their ipopt-equivalents ``print_level`` and ``max_iter``.

        """

        if not SCIPY_INSTALLED:

            msg = 'Install SciPy to use the minimize_ipopt function.'

>           raise ImportError(msg)

E           ImportError: Install SciPy to use the minimize_ipopt function.

cyipopt/scipy_interface.py:220: ImportError

During handling of the above exception, another exception occurred:

    @pytest.mark.skipif("scipy" in sys.modules,

                        reason="Test only valid if no Scipy available.")

    def test_minimize_ipopt_import_error_if_no_scipy():

        """`minimize_ipopt` not callable without SciPy installed."""

        expected_error_msg = re.escape("Install SciPy to use the "

                                       "`minimize_ipopt` function.")

        with pytest.raises(ImportError, match=expected_error_msg):

>           cyipopt.minimize_ipopt(None, None)

E           AssertionError: Regex pattern 'Install\\ SciPy\\ to\\ use\\ the\\ `minimize_ipopt`\\ function\\.' does not match 'Install SciPy to use the minimize_ipopt function.'.

cyipopt/tests/unit/test_scipy_optional.py:25: AssertionError

=========================== short test summary info ============================

FAILED cyipopt/tests/unit/test_scipy_optional.py::test_minimize_ipopt_import_error_if_no_scipy

==================== 1 failed, 6 passed, 3 skipped in 0.15s ====================

The command "pytest" exited with 1.
```

**Comment by moorepants** [comment]
The tests check the error message verbatim and I changed one.

**Comment by moorepants** [comment]
Ok, ready now.

**Review by brocksam — APPROVED** [review]
LGTM!

(Sorry for the delay in reviewing this, we've just had a four day public holiday in the UK because of Easter.)

**Comment by moorepants** [comment]
> (Sorry for the delay in reviewing this, we've just had a four day public holiday in the UK because of Easter.)

Same here in NL.

Thanks!

**Pull request merged**
