### PR TITLE
Improve the jax example

### LINKED ISSUE #144: improve the example "hs071_scipy_jax.py"
I found out that the current example "hs071_scipy_jax.py" can not find a optimal solution ,however, "hs071.py" does. The default float setting of JAX ("float32") leads to this unexcepted error. I handled this problem by the following code:

from jax.config import config
config.update("jax_enable_x64", True)

I hope we could highlght the importance of "float64" in cyipopt document(it seemed to be a default setting and may influence the evaluation) and update the example to help more user enjoy the combination of JAX and cyipopt.

### PR DESCRIPTION
**Pull request by jhelgert**
Fixes #144 and #145 .

### CODE REVIEW

**Comment by moorepants** [comment]
The tests fail on macosx only with python 3.9, giving:

```
Installed /usr/local/miniconda/envs/test-environment/lib/python3.9/site-packages/cyipopt-1.2.0.dev0-py3.9-macosx-10.9-x86_64.egg
Processing dependencies for cyipopt==1.2.0.dev0
Searching for cyipopt==1.2.0.dev0
Reading https://pypi.org/simple/cyipopt/
/usr/local/miniconda/envs/test-environment/lib/python3.9/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  warnings.warn(
No local packages or working download links found for cyipopt==1.2.0.dev0
error: Could not find suitable distribution for Requirement.parse('cyipopt==1.2.0.dev0')
Error: Process completed with exit code 1.
```

**Comment by moorepants** [comment]
This issue only being on Python 3.9 and Mac is odd:
```
Processing dependencies for cyipopt==1.2.0.dev0
Searching for cyipopt==1.2.0.dev0
Reading https://pypi.org/simple/cyipopt/
/usr/local/miniconda/envs/test-environment/lib/python3.9/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  warnings.warn(
No local packages or working download links found for cyipopt==1.2.0.dev0
error: Could not find suitable distribution for Requirement.parse('cyipopt==1.2.0.dev0')
Error: Process completed with exit code 1.
```

It is like it is searching pypi for a `cyipopt==1.20.dev0` to download. Not quite sure why it would be doing that. It thinks cyipopt is a dependency of itself.

**Comment by brocksam** [comment]
Our CI workflows is using [`python setup.py install`](https://github.com/mechmotum/cyipopt/blob/89401cf28345dd59137b272b95f13f0a6d481886/.github/workflows/test.yml#L31) to install CyIpopt. I think this is a hangover from distutils and might now be [deprecated](https://docs.python.org/3/install/). I wonder if using `pip install .` instead might fix the weird macOS-only bug?

**Comment by moorepants** [comment]
Oh me, if they remove `setup.py` that's going to bring back Py2->Py3-like pains.

We can try the pip command instead for this.

**Comment by moorepants** [comment]
@jhelgert Can you merge in master to get this https://github.com/mechmotum/cyipopt/pull/149?

**Comment by moorepants** [comment]
LGTM!

Thanks :)

**Pull request merged**
