### PR TITLE
Improve GitHub Actions

### PR DESCRIPTION
**Pull request by brocksam**
This PR addresses issues #113 and #124 by adding macOS and Windows to testing GitHub Action's matrix.

- `macos-latest` and `windows-latest` are added to the build matrix (`ubuntu-20.04` is changed to `ubuntu-latest`).
- A pre-existing GitHub action for installing miniconda (from [conda-incubator)](https://github.com/conda-incubator/setup-miniconda)) is added.
- Running of tests and test building documentation are split into two separate steps.

### CODE REVIEW

**Comment by brocksam** [comment]
This now tests (`.github/workflows/tests.yml`):

- Ipopt 3.12.x from conda-forge on macOS and Ubuntu for Python 3.6, 3.7, 3.8 and 3.9; and
- Ipopt 3.13.x and 3.14.x from conda-forge on Windows, macOS and Ubuntu for Python 3.6, 3.7, 3.8 and 3.9.

Two other actions are added:

- `.github/workflows/test.yml` runs the tests (the same as above), but on push and PR on all branches (but only on Ubuntu, Ipopt 3.14.x and Python 3.9). The idea here is that someone working on a PR on their own fork will be able to see the test sweet passing on any push to their fork.
- `.github/workflows/docs.yml` test builds the documentation. This has been separated as I didn't think it needed to be run on the full build matrix, and it makes it clearer when the docs failing to build is a problem if it's in its own separate Action.

Ipopt 3.12.x isn't tested on Windows as I don't think it's available on conda-forge. The old Appveyor script also tested Ipopt 3.11.x for backwards compatibility, as well as testing against the latest precompiled Ipopt from coin-or. @moorepants, do we want to add any of these?

**Comment by moorepants** [comment]
ipopt 3.11.9 is distributed with Ubuntu 20.04 LTS. The next LTS release is this coming april, so we probably shouldn't spend much effort on it any more. I'm fine with not testing for 3.11.

**Comment by moorepants** [comment]
So, are we not testing against coinor produced binaries on windows? I think that is a nice thing to have.

**Comment by brocksam** [comment]
> So, are we not testing against coinor produced binaries on windows? I think that is a nice thing to have.

Not currently, as I only noticed this after having set up the rest. But I will look into adding it and report back.

**Comment by brocksam** [comment]
> > So, are we not testing against coinor produced binaries on windows? I think that is a nice thing to have.
> 
> Not currently, as I only noticed this after having set up the rest. But I will look into adding it and report back.

Have spent a good few hours on this and cannot get it to work. Due to my lack of understanding of Windows and how GitHub Actions works with Windows. I suggest that we merge this as is in order the get the benefit from improved CI testing versus right now. And open a separate issue about testing with COIN-OR Windows binaries with GitHub Actions.

**Comment by brocksam** [comment]
> > > So, are we not testing against coinor produced binaries on windows? I think that is a nice thing to have.
> > 
> > 
> > Not currently, as I only noticed this after having set up the rest. But I will look into adding it and report back.
> 
> Have spent a good few hours on this and cannot get it to work. Due to my lack of understanding of Windows and how GitHub Actions works with Windows. I suggest that we merge this as is in order the get the benefit from improved CI testing versus right now. And open a separate issue about testing with COIN-OR Windows binaries with GitHub Actions.

Opened #140 for this.

**Comment by moorepants** [comment]
Sure, can you leave the appveryor yml file in then. I can still check that I believe and could try to link it back up to GH for the time being.

**Comment by moorepants** [comment]
Is this still WIP?

**Comment by brocksam** [comment]
> Is this still WIP?

No, my bad. Ready to merge if you're happy with it.

**Pull request merged**
