### PR TITLE
Adds configuration to use github actions for testing.

### LINKED ISSUE #120: Switch to Github Actions
Travis CI has abandoned their promise of free resources for open source projects. I had some credits when switching from travis-ci.org to travis-ci.com but they were very quickly consumed. Thus with #113 and no credits we have no CI testing. I've been switching my repos over to Github Actions (slowly), I think we should do the same here.

### PR DESCRIPTION
**Pull request by moorepants**
Fixes #120

### CODE REVIEW

**Comment by brocksam** [comment]
Hi @moorepants, not sure if you've done GitHub Actions with conda before, but I've found that a different approach was required to get CI working with conda than previously used with Travis.

You could try something like:

```
steps:
  - name: Checkout CyIpopt
    uses: actions/checkout@v2
  - uses: conda-incubator/setup-miniconda@v2
    with:
      auto-update-conda: true
      activate-environment: test-environment
      python-version: "3.9"
      channels: conda-forge
      conda-build-version: 3.21.4
  - name: Install basic dependencies
    run: # insert conda stuff here
  - name: Install CyIpopt
    run: python setup.py install
  - name: Test with pytest
    run: pytest tests/
```

**Comment by moorepants** [comment]
I am new to github actions. It seems overly complicated, to be honest. What I've got now runs at least. It could be improved more.

**Comment by moorepants** [comment]
I'm just going to merge as is. I'm not too keen on this marketplace, as it seems like you give up control of setting up your testing environment exactly the way you want to.

**Comment by brocksam** [comment]
> I'm just going to merge as is. I'm not too keen on this marketplace, as it seems like you give up control of setting up your testing environment exactly the way you want to.

I've setup GitHub Actions for a couple of projects now and agree that the learning curve was steeper than for other CI platforms. I think the use of certain actions from elsewhere can be helpful is simplifying setting up the automation of tasks beyond simply running the tests.

Happy for this to be merged as is as it's functioning. As you say, can always be extended/improved in future. The important thing is having functioning CI again :)

**Comment by moorepants** [comment]
Ok, Ill merge for now and we can switch to better implementations later. I am going to have to switch a ton of repos off Travis CI. So I'll learn all this soon it seems.

**Pull request merged**
