### PR TITLE
Add sanity checks to Jacobian / Hessian indices

### PR DESCRIPTION
**Pull request by chrhansk**
If the indices are not correct, then ipopt seems to segfault, so the errors should be caught earlier in the interface.

### CODE REVIEW

**Comment by moorepants** [comment]
Can you add some unit tests for these error messages?

**Comment by chrhansk** [comment]
I added tests for the Hessian. There is apparently a problem with the error handling in Ipopt itself (see coin-or/Ipopt/pull/697) which so far prevents error messages from the Jacobian evaluation being handled within Ipopt.

**Comment by chrhansk** [comment]
Edit: https://github.com/coin-or/Ipopt/pull/697 has been merged, so the bug in Ipopt should be fixed starting from version `3.14.13`. I added corresponding skipping conditions.

**Comment by moorepants** [comment]
Thanks for this contribution. LGTM.

**Pull request merged**
